version: '3'
services:
  eureka-server:
    image: lorenzo2017/eureka-server-image
    ports:
      - "8761:8761"
    
  api-gateway:
    image: lorenzo2017/api-gateway-image
    depends_on:
      - eureka-server
    ports:
      - "8085:8085"
    environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/

  ticket-service:
    image: lorenzo2017/ticket-ms-image
    depends_on:
      - api-gateway
    ports:
      - "6060:6060"
    environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/

  produto-service:
    image: lorenzo2017/produtos-ms-image
    depends_on:
      - ticket-service
    ports:
      - "6161:6161"
    environment:
        - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/


