spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      httpclient:
        connect-timeout: 200000
        response-timeout: 10m
      routes:
    
        - id: produto-service-route
          uri: lb://produto-service
          predicates:
            - Path=/produto/**
          filters:
            - StripPrefix=1

        - id: ticket-service-route
          uri: lb://ticket-service
          predicates:
            - Path=/ticket/**
          filters:
            - StripPrefix=1
          
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
          
server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DEFAULT_ZONE_SERVER:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true
    
