spring:
  application:
    name: produto-service

server:
  port: 6161

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${DEFAULT_ZONE_SERVER:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true
    
error:
 whitelabel:
   enabled: false 

   
