server: 
  port: 8761 
 
eureka:
  server:
     enable-self-preservation: true

  client: 
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl: 
      defaultZone: http://${DEFAULT_ZONE_SERVER:localhost}:8761/eureka/
