name: CI-CD-sample-microservices

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          docker build -t eureka-server-image ./eureka-server --quiet
          docker build -t api-gateway-image ./api-gateway --quiet
          docker build -t ticket-ms-image ./ticket-ms --quiet
          docker build -t produtos-ms-image ./produtos-ms --quiet

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server-image:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway-image:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ticket-ms-image:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/produtos-ms-image:latest

  deploy:

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose

      - name: Deploy microservices with Docker Compose
        run: |
          docker-compose -f docker-compose.yml pull
          docker-compose -f docker-compose.yml up -d

      - name: Wait for services to start
        run: sleep 30

      - name: Run tests (replace with your test commands)
        run: |
          # Add your test commands here

