name: CI-CD-sample-microservices

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          # Use a unique timestamp as a tag
          TIMESTAMP=$(date +%s)

          # Build and tag the images with the timestamp
          docker build -t eureka-server-image:$TIMESTAMP ./eureka-server --quiet
          docker build -t api-gateway-image:$TIMESTAMP ./api-gateway --quiet
          docker build -t ticket-ms-image:$TIMESTAMP ./ticket-ms --quiet
          docker build -t produtos-ms-image:$TIMESTAMP ./produtos-ms --quiet

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker images to Docker Hub
        run: |
          # Push the images with the timestamp as a tag
          TIMESTAMP=$(date +%s)
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server-image:$TIMESTAMP
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway-image:$TIMESTAMP
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ticket-ms-image:$TIMESTAMP
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/produtos-ms-image:$TIMESTAMP
